# Generated by Django 3.1 on 2020-08-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
