# Generated by Django 3.0.8 on 2020-07-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='url',
            field=models.URLField(default='https://www.buda.com/api/v2'),
            preserve_default=False,
        ),
    ]
